.PHONY:all
.PHONY:clean

all:
	$(MAKE) -C mega328p_firmware/grbl all
	$(MAKE) -C menutest_PC all
	$(MAKE) -C mega32_firmware all

clean:
	$(MAKE) -C mega328p_firmware/grbl clean
	$(MAKE) -C menutest_PC clean
	$(MAKE) -C mega32_firmware clean

